/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'id' : string,
  'curriculum' : Array<string>,
  'title' : string,
  'duration' : bigint,
  'prerequisites' : Array<string>,
  'instructor' : string,
  'difficulty' : string,
  'description' : string,
  'isFree' : boolean,
  'category' : string,
  'price' : bigint,
  'videos' : Array<Video>,
}
export type ExternalBlob = Uint8Array;
export interface Instructor {
  'id' : string,
  'bio' : string,
  'profileImage' : [] | [ExternalBlob],
  'name' : string,
  'qualifications' : Array<string>,
  'experience' : bigint,
}
export interface LiveClass {
  'id' : string,
  'startTime' : Time,
  'title' : string,
  'duration' : bigint,
  'recordingUrl' : [] | [string],
  'instructor' : string,
  'description' : string,
  'attendees' : Array<Principal>,
  'courseId' : string,
}
export interface Review {
  'userId' : Principal,
  'submittedAt' : Time,
  'comment' : string,
  'rating' : bigint,
  'courseId' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'enrolledCourses' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : string,
  'title' : string,
  'duration' : bigint,
  'order' : bigint,
  'contentUrl' : string,
  'isPaid' : boolean,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInstructor' : ActorMethod<[Instructor, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeVideo' : ActorMethod<[string], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCourse' : ActorMethod<[Course, string], undefined>,
  'createCourseWithoutAdminKey' : ActorMethod<[Course], undefined>,
  'enrollInCourse' : ActorMethod<[string], undefined>,
  'filterCoursesByCategory' : ActorMethod<[string], Array<Course>>,
  'filterCoursesByDifficulty' : ActorMethod<[string], Array<Course>>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllInstructors' : ActorMethod<[], Array<Instructor>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourse' : ActorMethod<[string], Course>,
  'getCourseAverageRating' : ActorMethod<[string], [] | [number]>,
  'getCourseReviews' : ActorMethod<[string], Array<Review>>,
  'getCourseVideos' : ActorMethod<[string], Array<Video>>,
  'getFreeCourses' : ActorMethod<[], Array<Course>>,
  'getInstructor' : ActorMethod<[string], [] | [Instructor]>,
  'getMyEnrolledCourses' : ActorMethod<[], Array<Course>>,
  'getPaidCourses' : ActorMethod<[], Array<Course>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUpcomingLiveClasses' : ActorMethod<[], Array<LiveClass>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideoContent' : ActorMethod<[string], Video>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'processCoursePayment' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'scheduleLiveClass' : ActorMethod<[LiveClass, string], undefined>,
  'setAdminKey' : ActorMethod<[string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitReview' : ActorMethod<[Review], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateVideoProgress' : ActorMethod<[string, bigint], undefined>,
  'verifyAdminKey' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];