/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Instructor = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'profileImage' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'qualifications' : IDL.Vec(IDL.Text),
  'experience' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Video = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'order' : IDL.Nat,
  'contentUrl' : IDL.Text,
  'isPaid' : IDL.Bool,
});
export const Course = IDL.Record({
  'id' : IDL.Text,
  'curriculum' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'prerequisites' : IDL.Vec(IDL.Text),
  'instructor' : IDL.Text,
  'difficulty' : IDL.Text,
  'description' : IDL.Text,
  'isFree' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'videos' : IDL.Vec(Video),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'enrolledCourses' : IDL.Vec(IDL.Text),
});
export const Time = IDL.Int;
export const Review = IDL.Record({
  'userId' : IDL.Principal,
  'submittedAt' : Time,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
  'courseId' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const LiveClass = IDL.Record({
  'id' : IDL.Text,
  'startTime' : Time,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'recordingUrl' : IDL.Opt(IDL.Text),
  'instructor' : IDL.Text,
  'description' : IDL.Text,
  'attendees' : IDL.Vec(IDL.Principal),
  'courseId' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInstructor' : IDL.Func([Instructor, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeVideo' : IDL.Func([IDL.Text], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCourse' : IDL.Func([Course, IDL.Text], [], []),
  'createCourseWithoutAdminKey' : IDL.Func([Course], [], []),
  'enrollInCourse' : IDL.Func([IDL.Text], [], []),
  'filterCoursesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Course)],
      ['query'],
    ),
  'filterCoursesByDifficulty' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Course)],
      ['query'],
    ),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllInstructors' : IDL.Func([], [IDL.Vec(Instructor)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourse' : IDL.Func([IDL.Text], [Course], ['query']),
  'getCourseAverageRating' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Float64)],
      ['query'],
    ),
  'getCourseReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getCourseVideos' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
  'getFreeCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getInstructor' : IDL.Func([IDL.Text], [IDL.Opt(Instructor)], ['query']),
  'getMyEnrolledCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getPaidCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUpcomingLiveClasses' : IDL.Func([], [IDL.Vec(LiveClass)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoContent' : IDL.Func([IDL.Text], [Video], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'processCoursePayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'scheduleLiveClass' : IDL.Func([LiveClass, IDL.Text], [], []),
  'setAdminKey' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitReview' : IDL.Func([Review], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateVideoProgress' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'verifyAdminKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Instructor = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'profileImage' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'qualifications' : IDL.Vec(IDL.Text),
    'experience' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Video = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'order' : IDL.Nat,
    'contentUrl' : IDL.Text,
    'isPaid' : IDL.Bool,
  });
  const Course = IDL.Record({
    'id' : IDL.Text,
    'curriculum' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'prerequisites' : IDL.Vec(IDL.Text),
    'instructor' : IDL.Text,
    'difficulty' : IDL.Text,
    'description' : IDL.Text,
    'isFree' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'videos' : IDL.Vec(Video),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'enrolledCourses' : IDL.Vec(IDL.Text),
  });
  const Time = IDL.Int;
  const Review = IDL.Record({
    'userId' : IDL.Principal,
    'submittedAt' : Time,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
    'courseId' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const LiveClass = IDL.Record({
    'id' : IDL.Text,
    'startTime' : Time,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'recordingUrl' : IDL.Opt(IDL.Text),
    'instructor' : IDL.Text,
    'description' : IDL.Text,
    'attendees' : IDL.Vec(IDL.Principal),
    'courseId' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInstructor' : IDL.Func([Instructor, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeVideo' : IDL.Func([IDL.Text], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCourse' : IDL.Func([Course, IDL.Text], [], []),
    'createCourseWithoutAdminKey' : IDL.Func([Course], [], []),
    'enrollInCourse' : IDL.Func([IDL.Text], [], []),
    'filterCoursesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Course)],
        ['query'],
      ),
    'filterCoursesByDifficulty' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Course)],
        ['query'],
      ),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllInstructors' : IDL.Func([], [IDL.Vec(Instructor)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourse' : IDL.Func([IDL.Text], [Course], ['query']),
    'getCourseAverageRating' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Float64)],
        ['query'],
      ),
    'getCourseReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'getCourseVideos' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
    'getFreeCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getInstructor' : IDL.Func([IDL.Text], [IDL.Opt(Instructor)], ['query']),
    'getMyEnrolledCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getPaidCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUpcomingLiveClasses' : IDL.Func([], [IDL.Vec(LiveClass)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoContent' : IDL.Func([IDL.Text], [Video], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'processCoursePayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'scheduleLiveClass' : IDL.Func([LiveClass, IDL.Text], [], []),
    'setAdminKey' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitReview' : IDL.Func([Review], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateVideoProgress' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'verifyAdminKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };